version: '3.1'

services:
  db:
    image: postgres:13.7
    privileged: true
    restart: always
    ports:
      - 54327:5432
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'backend'

  backend:
    build: ./backend
    privileged: true
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    command: bash -c "
      python manage.py migrate && 
      gunicorn backend.wsgi -b 0.0.0.0:8080
      "
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings.prod